<a href="https://colab.research.google.com/github/prathamesh144/SKILL/blob/main/expt3.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

Connecting Google Drive

In [ ]:
from google.colab import drive
drive.mount('/content/drive')

Mounted at /content/drive

Importing Dataset

In [ ]:
import pandas as pd
data=pd.read_csv('/content/drive/MyDrive/Data_Science/Netflix_data.csv')

,title,type,genres,releaseYear,imdbId,imdbAverageRating,imdbNumVotes,availableCountries
0,The Fifth Element,movie,"Action, Adventure, Sci-Fi",1997.0,tt0119116,7.6,518984.0,"AT, CH, DE"
1,Kill Bill: Vol. 1,movie,"Action, Crime, Thriller",2003.0,tt0266697,8.2,1227719.0,"AE, AL, AO, AT, AU, AZ, BG, BH, BY, CA, CI, CM..."
2,Jarhead,movie,"Biography, Drama, War",2005.0,tt0418763,7.0,212629.0,"AD, AE, AG, AO, BH, BM, BR, BS, BZ, CI, CM, CO..."
3,Unforgiven,movie,"Drama, Western",1992.0,tt0105695,8.2,446373.0,"AU, BA, BG, CZ, HR, HU, MD, ME, MK, NZ, PL, RO..."
4,Eternal Sunshine of the Spotless Mind,movie,"Drama, Romance, Sci-Fi",2004.0,tt0338013,8.3,1112555.0,"AD, AE, AG, AL, AO, AR, AU, AZ, BA, BB, BE, BG..."

displaying information

In [ ]:
data.head()
data.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 20490 entries, 0 to 20489
Data columns (total 8 columns):
 #   Column              Non-Null Count  Dtype
---  ------              --------------  -----
 0   title               19927 non-null  object
 1   type                20490 non-null  object
 2   genres              20187 non-null  object
 3   releaseYear         20469 non-null  float64
 4   imdbId              19081 non-null  object
 5   imdbAverageRating   18918 non-null  float64
 6   imdbNumVotes        18918 non-null  float64
 7   availableCountries  20490 non-null  object
dtypes: float64(3), object(5)
memory usage: 1.3+ MB

In [ ]:
from sklearn.preprocessing import LabelEncoder
le=LabelEncoder()

1. Label Encoding

In [ ]:
data['title'].fillna('Unknown', inplace=True)
data['genres'].fillna('Unknown', inplace=True)
data['releaseYear'].fillna(data['releaseYear'].median(), inplace=True)
data['imdbAverageRating'].fillna(data['imdbAverageRating'].median(), inplace=True)
data['imdbNumVotes'].fillna(data['imdbNumVotes'].median(), inplace=True)

<ipython-input-5-6e7bde613327>:1: FutureWarning: A value is trying to be set on a copy of a DataFrame or Series through chained assignment using an inplace method.
The behavior will change in pandas 3.0. This inplace method will never work because the intermediate object on which we are setting values always behaves as a copy.

For example, when doing 'df[col].method(value, inplace=True)', try using 'df.method({col: value}, inplace=True)' or df[col] = df[col].method(value) instead, to perform the operation inplace on the original object.


  data['title'].fillna('Unknown', inplace=True)
<ipython-input-5-6e7bde613327>:2: FutureWarning: A value is trying to be set on a copy of a DataFrame or Series through chained assignment using an inplace method.
The behavior will change in pandas 3.0. This inplace method will never work because the intermediate object on which we are setting values always behaves as a copy.

For example, when doing 'df[col].method(value, inplace=True)', try using 'df.method({col: value}, inplace=True)' or df[col] = df[col].method(value) instead, to perform the operation inplace on the original object.


  data['genres'].fillna('Unknown', inplace=True)
<ipython-input-5-6e7bde613327>:3: FutureWarning: A value is trying to be set on a copy of a DataFrame or Series through chained assignment using an inplace method.
The behavior will change in pandas 3.0. This inplace method will never work because the intermediate object on which we are setting values always behaves as a copy.

For example, when doing 'df[col].method(value, inplace=True)', try using 'df.method({col: value}, inplace=True)' or df[col] = df[col].method(value) instead, to perform the operation inplace on the original object.


  data['releaseYear'].fillna(data['releaseYear'].median(), inplace=True)
<ipython-input-5-6e7bde613327>:4: FutureWarning: A value is trying to be set on a copy of a DataFrame or Series through chained assignment using an inplace method.
The behavior will change in pandas 3.0. This inplace method will never work because the intermediate object on which we are setting values always behaves as a copy.

For example, when doing 'df[col].method(value, inplace=True)', try using 'df.method({col: value}, inplace=True)' or df[col] = df[col].method(value) instead, to perform the operation inplace on the original object.


  data['imdbAverageRating'].fillna(data['imdbAverageRating'].median(), inplace=True)
<ipython-input-5-6e7bde613327>:5: FutureWarning: A value is trying to be set on a copy of a DataFrame or Series through chained assignment using an inplace method.
The behavior will change in pandas 3.0. This inplace method will never work because the intermediate object on which we are setting values always behaves as a copy.

For example, when doing 'df[col].method(value, inplace=True)', try using 'df.method({col: value}, inplace=True)' or df[col] = df[col].method(value) instead, to perform the operation inplace on the original object.


  data['imdbNumVotes'].fillna(data['imdbNumVotes'].median(), inplace=True)

2. Label Encoding for type

In [ ]:
label_encoder = LabelEncoder()
data['type'] = label_encoder.fit_transform(data['type'])

One Hot Encoding

In [ ]:
top_genres = data['genres'].str.split(',').explode().value_counts().head(5).index
for genre in top_genres:
    data[f'genre_{genre}'] = data['genres'].apply(lambda x: 1 if genre in x else 0)

Frequency Encoding

In [ ]:
data['country_count'] = data['availableCountries'].apply(lambda x: len(str(x).split(',')))

Data Showing

In [ ]:
data_processed = data.drop(['title', 'genres', 'imdbId', 'availableCountries'], axis=1)

In [ ]:
data_processed.head()

,type,releaseYear,imdbAverageRating,imdbNumVotes,genre_Comedy,genre_ Drama,genre_Drama,genre_Action,genre_ Romance,country_count
0,0,1997.0,7.6,518984.0,0,0,0,1,0,3
1,0,2003.0,8.2,1227719.0,0,0,0,1,0,68
2,0,2005.0,7.0,212629.0,0,1,1,0,0,70
3,0,1992.0,8.2,446373.0,0,0,1,0,0,15
4,0,2004.0,8.3,1112555.0,0,0,1,0,1,126