<a href="https://colab.research.google.com/github/prathamesh144/SKILL/blob/main/Untitled13.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [5]:
import pandas as pd
import seaborn as sns
import numpy as np
from IPython.display import display

In [6]:
data=pd.read_csv('heart.csv')

In [7]:
display(data.info(),
        data.describe(),
        data.shape,
        data.size,
        data.head()
        )

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 1025 entries, 0 to 1024
Data columns (total 14 columns):
 #   Column    Non-Null Count  Dtype
---  ------    --------------  -----
 0   age       1025 non-null   int64
 1   sex       1025 non-null   int64
 2   cp        1025 non-null   int64
 3   trestbps  1025 non-null   int64
 4   chol      1025 non-null   int64
 5   fbs       1025 non-null   int64
 6   restecg   1025 non-null   int64
 7   thalach   1025 non-null   int64
 8   exang     1025 non-null   int64
 9   oldpeak   1025 non-null   float64
 10  slope     1025 non-null   int64
 11  ca        1025 non-null   int64
 12  thal      1025 non-null   int64
 13  target    1025 non-null   int64
dtypes: float64(1), int64(13)
memory usage: 112.2 KB

None

,age,sex,cp,trestbps,chol,fbs,restecg,thalach,exang,oldpeak,slope,ca,thal,target
count,1025.000000,1025.000000,1025.000000,1025.000000,1025.00000,1025.000000,1025.000000,1025.000000,1025.000000,1025.000000,1025.000000,1025.000000,1025.000000,1025.000000
mean,54.434146,0.695610,0.942439,131.611707,246.00000,0.149268,0.529756,149.114146,0.336585,1.071512,1.385366,0.754146,2.323902,0.513171
std,9.072290,0.460373,1.029641,17.516718,51.59251,0.356527,0.527878,23.005724,0.472772,1.175053,0.617755,1.030798,0.620660,0.500070
min,29.000000,0.000000,0.000000,94.000000,126.00000,0.000000,0.000000,71.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000
25%,48.000000,0.000000,0.000000,120.000000,211.00000,0.000000,0.000000,132.000000,0.000000,0.000000,1.000000,0.000000,2.000000,0.000000
50%,56.000000,1.000000,1.000000,130.000000,240.00000,0.000000,1.000000,152.000000,0.000000,0.800000,1.000000,0.000000,2.000000,1.000000
75%,61.000000,1.000000,2.000000,140.000000,275.00000,0.000000,1.000000,166.000000,1.000000,1.800000,2.000000,1.000000,3.000000,1.000000
max,77.000000,1.000000,3.000000,200.000000,564.00000,1.000000,2.000000,202.000000,1.000000,6.200000,2.000000,4.000000,3.000000,1.000000

(1025, 14)

14350

,age,sex,cp,trestbps,chol,fbs,restecg,thalach,exang,oldpeak,slope,ca,thal,target
0,52,1,0,125,212,0,1,168,0,1.0,2,2,3,0
1,53,1,0,140,203,1,0,155,1,3.1,0,0,3,0
2,70,1,0,145,174,0,1,125,1,2.6,0,0,3,0
3,61,1,0,148,203,0,1,161,0,0.0,2,1,3,0
4,62,0,0,138,294,1,1,106,0,1.9,1,3,2,0

In [8]:
print("NAN")
nan_counts = data.isna().sum()
print(nan_counts[nan_counts > 0])

print("\nNULL")
null_counts = data.isnull().sum()
print(null_counts[null_counts > 0])

NAN
Series([], dtype: int64)

NULL
Series([], dtype: int64)

In [11]:
from sklearn.preprocessing import StandardScaler
def scalling(data):
    numeric_data = data.select_dtypes(include=['float64', 'int64'])
    scaler = StandardScaler()
    scaled_data = scaler.fit_transform(numeric_data)
    scaled_df = pd.DataFrame(scaled_data, columns=numeric_data.columns)
    return scaled_df

In [12]:
scalled_data=scalling(data)

In [13]:
scalled_x=scalled_data.iloc[:,:-1]
scalled_y=scalled_data.iloc[:,-1]

Filter method

In [14]:
from sklearn.feature_selection import VarianceThreshold
def varience(data):

    numeric_data = data.select_dtypes(include=['float64', 'int64'])
    selector = VarianceThreshold(threshold=0.2)

    selected_data = selector.fit_transform(data)

    selected_features = numeric_data.columns[selector.get_support()]

    features_removed = [col for col in numeric_data.columns if col not in selected_features]


    print(f"Original features: {numeric_data.shape[1]}")
    print(f"Features after variance thresholding: {selected_data.shape[1]}")
    print(f"Features removed: {numeric_data.shape[1] - selected_data.shape[1]}")
    print("\nSelected features:")
    print(selected_features.tolist())
    print("\nremoved features:")
    print(features_removed)
    final_data = data[selected_features]
    return final_data

In [15]:
scaled=scalling(data)
varience(scaled)

Original features: 14
Features after variance thresholding: 14
Features removed: 0

Selected features:
['age', 'sex', 'cp', 'trestbps', 'chol', 'fbs', 'restecg', 'thalach', 'exang', 'oldpeak', 'slope', 'ca', 'thal', 'target']

removed features:
[]

,age,sex,cp,trestbps,chol,fbs,restecg,thalach,exang,oldpeak,slope,ca,thal,target
0,-0.268437,0.661504,-0.915755,-0.377636,-0.659332,-0.418878,0.891255,0.821321,-0.712287,-0.060888,0.995433,1.209221,1.089852,-1.026698
1,-0.158157,0.661504,-0.915755,0.479107,-0.833861,2.387330,-1.004049,0.255968,1.403928,1.727137,-2.243675,-0.731971,1.089852,-1.026698
2,1.716595,0.661504,-0.915755,0.764688,-1.396233,-0.418878,0.891255,-1.048692,1.403928,1.301417,-2.243675,-0.731971,1.089852,-1.026698
3,0.724079,0.661504,-0.915755,0.936037,-0.833861,-0.418878,0.891255,0.516900,-0.712287,-0.912329,0.995433,0.238625,1.089852,-1.026698
4,0.834359,-1.511706,-0.915755,0.364875,0.930822,2.387330,0.891255,-1.874977,-0.712287,0.705408,-0.624121,2.179817,-0.522122,-1.026698
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
1020,0.503520,0.661504,0.055931,0.479107,-0.484803,-0.418878,0.891255,0.647366,1.403928,-0.912329,0.995433,-0.731971,-0.522122,0.973997
1021,0.613800,0.661504,-0.915755,-0.377636,0.232705,-0.418878,-1.004049,-0.352873,1.403928,1.471705,-0.624121,0.238625,1.089852,-1.026698
1022,-0.819834,0.661504,-0.915755,-1.234378,0.562371,-0.418878,-1.004049,-1.353113,1.403928,-0.060888,-0.624121,0.238625,-0.522122,-1.026698
1023,-0.488996,-1.511706,-0.915755,-1.234378,0.155137,-0.418878,-1.004049,0.429923,-0.712287,-0.912329,0.995433,-0.731971,-0.522122,0.973997
1024,-0.047877,0.661504,-0.915755,-0.663216,-1.124743,-0.418878,0.891255,-1.570556,-0.712287,0.279688,-0.624121,0.238625,1.089852,-1.026698

In [16]:
def corr(data):
    numeric_data = data.select_dtypes(include=['float64', 'int64'])

    corr_matrix = pd.DataFrame(numeric_data).corr().abs()

    upper = corr_matrix.where(np.triu(np.ones(corr_matrix.shape), k=1).astype(bool))

    to_drop = [column for column in upper.columns if any(upper[column] > 0.8)]
    print(to_drop)
    data_selected = pd.DataFrame(data).drop(to_drop, axis=1)

    return data_selected

In [17]:
def corr(data):
    numeric_data = data.select_dtypes(include=['float64', 'int64'])

    corr_matrix = pd.DataFrame(numeric_data).corr().abs()

    upper = corr_matrix.where(np.triu(np.ones(corr_matrix.shape), k=1).astype(bool))

    to_drop = [column for column in upper.columns if any(upper[column] > 0.8)]
    print(to_drop)
    data_selected = pd.DataFrame(data).drop(to_drop, axis=1)

    return data_selected

In [18]:
corr(scaled)

[]

,age,sex,cp,trestbps,chol,fbs,restecg,thalach,exang,oldpeak,slope,ca,thal,target
0,-0.268437,0.661504,-0.915755,-0.377636,-0.659332,-0.418878,0.891255,0.821321,-0.712287,-0.060888,0.995433,1.209221,1.089852,-1.026698
1,-0.158157,0.661504,-0.915755,0.479107,-0.833861,2.387330,-1.004049,0.255968,1.403928,1.727137,-2.243675,-0.731971,1.089852,-1.026698
2,1.716595,0.661504,-0.915755,0.764688,-1.396233,-0.418878,0.891255,-1.048692,1.403928,1.301417,-2.243675,-0.731971,1.089852,-1.026698
3,0.724079,0.661504,-0.915755,0.936037,-0.833861,-0.418878,0.891255,0.516900,-0.712287,-0.912329,0.995433,0.238625,1.089852,-1.026698
4,0.834359,-1.511706,-0.915755,0.364875,0.930822,2.387330,0.891255,-1.874977,-0.712287,0.705408,-0.624121,2.179817,-0.522122,-1.026698
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
1020,0.503520,0.661504,0.055931,0.479107,-0.484803,-0.418878,0.891255,0.647366,1.403928,-0.912329,0.995433,-0.731971,-0.522122,0.973997
1021,0.613800,0.661504,-0.915755,-0.377636,0.232705,-0.418878,-1.004049,-0.352873,1.403928,1.471705,-0.624121,0.238625,1.089852,-1.026698
1022,-0.819834,0.661504,-0.915755,-1.234378,0.562371,-0.418878,-1.004049,-1.353113,1.403928,-0.060888,-0.624121,0.238625,-0.522122,-1.026698
1023,-0.488996,-1.511706,-0.915755,-1.234378,0.155137,-0.418878,-1.004049,0.429923,-0.712287,-0.912329,0.995433,-0.731971,-0.522122,0.973997
1024,-0.047877,0.661504,-0.915755,-0.663216,-1.124743,-0.418878,0.891255,-1.570556,-0.712287,0.279688,-0.624121,0.238625,1.089852,-1.026698

In [19]:

from sklearn.feature_selection import chi2
from sklearn.model_selection import train_test_split

def chi2test(data):
    x=data.iloc[:,:-1]
    y=data.iloc[:,-1]
    columns_selected= chi2(x,y)
    p_values=pd.Series(columns_selected[1])
    p_values.index=x.columns
    return p_values.sort_index(ascending=False)

In [20]:
chi2test(data)

trestbps     1.198287e-11
thalach     2.224662e-143
thal         1.074903e-05
slope        6.516763e-09
sex          7.934661e-07
restecg      1.803654e-03
oldpeak      4.149300e-57
fbs          2.241583e-01
exang        3.232318e-30
cp           2.698064e-49
chol         6.803149e-26
ca           1.003018e-47
age          1.820066e-19
dtype: float64

In [21]:

from sklearn.feature_selection import SelectKBest, f_classif
def anovatest(data):
    x=data.iloc[:,:-1]
    y=data.iloc[:,-1]
    xtrain,xtest,ytrain,ytest=train_test_split(x,y,test_size=0.2,random_state=1)
    selector = SelectKBest(f_classif)
    X_selected = selector.fit_transform(xtrain, ytrain)

    f_scores = selector.scores_
    p_values = selector.pvalues_

    feature_scores = pd.DataFrame({
        'Feature': xtrain.columns,
        'F Score': f_scores,
        'P Value': p_values
    })

    feature_scores = feature_scores.sort_values('F Score', ascending=False)
    print(feature_scores.head(10))

In [22]:
anovatest(data)

    Feature     F Score       P Value
8     exang  203.626002  2.038245e-41
2        cp  199.677192  1.001204e-40
9   oldpeak  195.049727  6.517764e-40
7   thalach  182.435869  1.125442e-37
11       ca  131.481674  2.486529e-28
12     thal  119.605602  4.455097e-26
10    slope  117.018888  1.392035e-25
1       sex   73.331123  5.397681e-17
0       age   46.704383  1.612822e-11
6   restecg   21.955759  3.266880e-06

In [23]:

from sklearn.feature_selection import mutual_info_classif, SelectKBest
def mutualinfotest(data):
    x=data.iloc[:,:-1]
    y=data.iloc[:,-1]
    xtrain,xtest,ytrain,ytest=train_test_split(x,y,test_size=0.2,random_state=1)
    selector = SelectKBest(mutual_info_classif, k=10)
    X_selected = selector.fit_transform(xtrain, ytrain)

    f_scores = selector.scores_

    feature_scores = pd.DataFrame({
        'Feature': xtrain.columns,
        'F Score': f_scores,
    })

    feature_scores = feature_scores.sort_values('F Score', ascending=False)
    print(feature_scores.head(10))

In [24]:
mutualinfotest(data)

    Feature   F Score
4      chol  0.252010
9   oldpeak  0.161747
7   thalach  0.156125
12     thal  0.126898
2        cp  0.125572
8     exang  0.099621
11       ca  0.096027
0       age  0.070987
10    slope  0.065602
1       sex  0.037119